### ISSUE TITLE
streaming music is not playing

### ISSUE THREAD

**Issue by y0zhyck** [umutxyp/MusicBot#103]
Yesterday it became interesting whether this miracle is able to produce streaming music, as a result, the bot does not understand, for example, took this link https://www.youtube.com/live/jfKfPfyJRdk ?feature=share

how to fix?

**Comment by BlackusPL** [comment]
use https://www.youtube.com/watch?v=jfKfPfyJRdk instead of */live/* becouse bot dont understand redirect links
