### ISSUE TITLE
volume in config.js not being applied

### ISSUE THREAD

**Issue by jchrist188** [umutxyp/MusicBot#108]
changing value maxVol in config.js is not being changed in bot audio levels. bot audio appears to be full volume despite /nowplaying volume showing 50% and config.js set to 25

![image](https://user-images.githubusercontent.com/130275532/230759738-02ef1752-d295-4f53-9971-2672119daa1b.png)

**Comment by lxgg142** [comment]
create a new file initQueue.js in events/player and try to include that:

`module.exports = async (client, queue) => {
  queue.volume = client.config.opt.maxVol
};`

**Reminder:** i haven't tried it

**Comment by omgomghax** [comment]
**player.setVolume(25);**

add this below **const player = client.player;**

i guess [lxgg142](https://github.com/lxgg142)'s reply could work while i didnt try it but with **queue.setVolume**
