### ISSUE TITLE
mongodb error 

### ISSUE THREAD

**Issue by neylhokage** [umutxyp/MusicBot#109]
when i run the bot i have this error 
MongoDB Error: MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/

WARN: It looks like you didn't write the mongodb url? If you do not enter a valid mongodb url in the config.js file, you will not be able to use the bot.
but i wrote mongodb url correctly and yesterday it worked fine
pls help me with this issue

**Comment by MrDick004** [comment]
Hi, the same error happened to me for no apparent reason, the code never touched, however I solved it by deleting the "node_modules" folder and reinstalling everything with "npm install", the bot recognizes the MongoDB database again

**Comment by MrDick004** [comment]
You're right, it only worked for me for 4 hours, but now it gives me the error again that it can't find the mongoDB database, I also tried putting the IP address back in "network access" of MongoDB but nothing, I can't figure out what it's due to, I also tried updating the dependencies but nothing changed. Even on the internet I can't find a solution.

**Comment by neylhokage** [comment]
that is pretty upset. but thanks for help)

**Comment by omgomghax** [comment]
Check if this is ok

![image](https://user-images.githubusercontent.com/77762700/231576554-5984737c-c412-4685-b38e-99d8a74e4716.png)

**Comment by MrDick004** [comment]
We already tried, and yes, everything is correct, as we mentioned it happened suddenly, nothing was touched, if the link was wrong it didn't work for me at all, instead it works for me almost intermittently, even updating the Mongoose dependency didn't fix anything, if I delete the "node_modules" folder and reinstall everything I get the bot working correctly for an hour and then the MongoDB error that can't find the database starts again, I don't know, maybe there is a bug in the dependencies or I really have no idea.

**Comment by lxgg142** [comment]
if using a local database try changing the MongoDB URI from localhost to 127.0.0.1

**Comment by omgomghax** [comment]
i'd suggest you download and try mongodb Compass and see if you are getting disconnected from there as well.
If the disconnection occurs in there as well, i think your problem is either with the IP getting blacklisted for some reason, or wrong  cloud mongodb settings.

**Comment by Gamulation** [comment]
You need to go on mongodb and ad the following IP address to your cluster: 0.0.0.0/0
after that the bot should work.

**Comment by MrDick004** [comment]
I solved it by simply changing Hosting service, for some arcane mysterious reason replit after 2/3 hours that the bot is on sends the IP address blacklisted for mongoDB or vice versa.
