### ISSUE TITLE
update Japanese file and bug fix

### ISSUE THREAD

**Issue by Hoshimikan6490** [umutxyp/MusicBot#118]
I updated ja.js.
The reason is written in #117 .

**Comment by byorage** [comment]
hi,

just to tell you that with the addition of the Japanese language the **/language** command no longer works.

**Comment by Hoshimikan6490** [comment]
> hi,
> 
> just to tell you that with the addition of the Japanese language the **/language** command no longer works.

Oh, I see. As soon as I will check program of my branch.

**Comment by Hoshimikan6490** [comment]
@byorage 
Thank you for your message. I fixed that bug.
Its change is in #117 .
