### ISSUE TITLE
No issue but a suggestion

### ISSUE THREAD

**Issue by ItsNyoty** [umutxyp/MusicBot#12]
Please add lyrics

**Comment by 1umutda** [comment]
soon.

**Comment by NotSoMik** [comment]
About the queue command can you add some buttons so we can see all songs

**Comment by 1umutda** [comment]
> Please add lyrics

added. good luck

**Comment by 1umutda** [comment]
> About the queue command can you add some buttons so we can see all songs

soon :)

**Comment by NotSoMik** [comment]
👍🏻

**Comment by 1umutda** [comment]
> 👍🏻

https://github.com/1umutda/MusicBot/blob/main/commands/queue.js
added. GOOD LUCK :)

**Comment by NotSoMik** [comment]
Nice 👍🏻

**Comment by ItsNyoty** [comment]
please add shuffle

**Comment by umutxyp** [comment]
test
