### ISSUE TITLE
when I host online the bot doesn't play the music, the bot enters and exits

### ISSUE THREAD

**Issue by RedMemories** [umutxyp/MusicBot#130]
hi, I'm writing this issue because I don't know how to solve it, and I don't know if anyone has the same problem as me, basically when I host my discord bot online, the music doesn't start, the bot enters it says there is music and exits saying that's over, if I host it locally from my pc everything works
(sorry for my english)

**Comment by MrPondi** [comment]
i have the same exact problem

**Comment by y0zhyck** [comment]
Also happened recently

**Comment by Tundra-Shark** [comment]
Your server does not have FFmpeg, so you will need to install FFmpeg on it. Despite the fact that `package.json` does include `ffmpeg` and `ffmpeg-static`, that is not enough and you will need to install the binaries.

For example, here are the steps I used on my Rocky Linux server:

https://computingforgeeks.com/install-use-ffmpeg-on-rocky-alma-9/

```
sudo dnf install epel-release
sudo dnf config-manager --set-enabled crb
sudo dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm -y
sudo dnf install --nogpgcheck https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y
sudo dnf install ffmpeg ffmpeg-devel
```

**Comment by umutxyp** [comment]
Try different virtual machines and if you are using the npm install command, download modules such as ffmpeg, ffmpeg-static, distube individually, not as a bulk download.
