### ISSUE TITLE
Stupid node

### ISSUE THREAD

**Issue by gizmoantic** [umutxyp/MusicBot#135]
Way the fuck always it says npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'musicbot-v14.11@15.3.0',
npm WARN EBADENGINE   required: { node: '17.x' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }

when i want to install somthing and when i tryd instaliin node 17.x it sayd npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'musicbot-v14.11@15.3.0',
npm WARN EBADENGINE   required: { node: '17.x' },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }

pls help me

**Comment by InvalidKaro** [comment]
no

**Comment by AvuxyOff** [comment]
do in replit
