### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by y0zhyck** [umutxyp/MusicBot#143]
Hi all, I faced such a problem that I can not update npm when entering the combination npm install comes up a bunch of errors (you can see on the screenshot).
![image](https://github.com/umutxyp/MusicBot/assets/38162408/71ce62e6-a898-4159-a98c-8a89b09333fb)

**Comment by delidolu1adam** [comment]
I think the bot needs to be updated. I also encountered many errors and I am using a different bot now. The bot developer has already removed the files. I hope they update it soon.

**Comment by umutxyp** [comment]
updated
