### ISSUE TITLE
Bot geliştirmesi için bazı tavsiyeler.

### ISSUE THREAD

**Issue by delidolu1adam** [umutxyp/MusicBot#145]
Selam Umut, öncelikle bot için teşekkür ederim. Açık kaynaklı ve herkes tarafından kullanılabilir olması gerçekten çok güzel. Günümüzdeki premium botlardan ve 1 müzik oynatıp kanaldan ayrılan botlardan çok sıkıldık.

Botunu geliştirmeyi düşünürsen bir kaç önerim olacak. Eğer vakit buldukça botunu bu yönde geliştirirsen ve bu gelişmeleri yine bizimle paylaşırsan çok memnun olurum.

1: 24/7 desteği.
- Bot belirtilen saniye boyunca kanalda kalır ve süre dolduğunda otomatik ayrılır. Örneğin 1 saatlik bir süre için BOT_STAY_TIME = "600000"

2: Dj Rolü atama.
- Sunucuda herhangi bir role DJ rolünü atayarak, botun skip vb. komutlarını sadece bu rol varsa kullanabilmeyi sağlama.

3: /play normal komutu ve bazı ek komut geliştirmeleri.
- Komut listesini daha kullanışlı ve zengin hale getirebilirsin.

/play şarkı adı veya url
/playlist oynatma listesi url
/live canlı yayın url

Örneğin "music, radio, general, moderation, fun" vb. klasör isimleriyle "commands" klasörü içindeki komutları da klasörler halinde ayırabilirsin. 

Yine aynı şekilde bir kaç API kullanarak bota bir kaç yeni özellik eklenebilir.

/search "metin şentürk kimdir?" yazılan içeriği internette yada wiki de arama yapar.
/lyrics mecvut çalan şarkının sözlerini gösterir.
/translate "hello world" metnini türkçeye çevirir.
/clear "100" sohbet kanalındaki son 100 mesajı siler.
/mute kullanıcıyı susturur
/unmute kullanıcının sesini açar
/kick kullanıcıyı sunucudan atar
/disc kullanıcının sunucu ile bağlantısını keser
/ban kullanıcıyı yasaklar
/unban kullanıcı yasağını kaldırır
/move kullanıcıyı belirtilen kanala taşır

Yine bunlara ek olarak "twitch, youtube, instagram, twitter, tiktok" vb. platformlardaki kanal url lerinini ekleyerek belirlenen kanala bildirim almayı sağlayabiliriz.

/notice add kanalURL
/notice remove kanalURL
/streamchannel bildirimler belirkenen kanala alınır.
/removestreamchannel kanalı siler.

Yine bunlara ek olarak "steam, epicgames, gog, ubisoft, ea" vb. platformlardaki ücretsiz oyunları istenirse 50% ve üstündeki indirimleri bildirim oalrak belirlenen kanala almayı sağlayabiliriz.

/gamenotice add steam
/gamenotice remove steam
/gamechannel bildirimler belirkenen kanala alınır.
/removegamechannel kanalı siler.

4: Dil seçme menüsü için SELECT opsiyonunu kullanabilirsin.
- /language komutu kullanıldığında aşağıdaki gibi bir seçme menüsü oluşursa daha güzel görünür.

<select name="language">
<option value="beyaz">[Bayrak] Türkçe</option>
 <option value="kirmizi">[Bayrak] English</option>
<option value="siyah">[Bayrak] Français</option>
</select>

5: /help komutu arayüzünü kategorize edebilirsin.
- Yönetici, Genel, Müzik Çalar, Eğlence, Yardım vb. şekilde.

**Comment by umutxyp** [comment]
Merhaba teşekkürler ancak bir kaç talebiniz dışında hiç bir istek müzik botu kavramına uymuyor. Proje müzik projesi o yüzden bence amacına hizmet etmelidir. Ek olarak çok yüksek oranla bu projeye birdaha güncelleme gelmeyecek sadece discord botumuz için kişisel güncellemeler gelebilir. Ücretsiz açık kaynak kod paylaşımını uzun vadede durdurdum yakında proje githubdan taşınacak.
