### ISSUE TITLE
Command Suggestions

### ISSUE THREAD

**Issue by inflicting** [umutxyp/MusicBot#19]
lyrics - displays lyrics (would need genius.com api)
skip - needs votes from everyone in the vc to skip a song (send a message "do you want to skip this song?" + ✔ & ❌ reaction on the message)
skipto - skip to a specific song in queue
forceskip - force skip a song (no votes needed)
removedupes - removes duplicate songs in queue
seek hh:mm:ss - go to a specific part of a song
join - joins channel
leave - leaves channel
speed - change song speed
pitch - change song pitch
remove (number) - removes a specific song from queue
cleanup - removes songs from users which left the voice channel
repeatqueue - repeat the current queue
announce - toggles the now playing messages
pruning - toggles pruning. If its enabled "now playing" messages will be deleted automatically when a song finishes.
playlist list
playlist [view/load/create/delete/edit] [playlist name]
playlist add [playlist name], [track name/link]
playlist remove [playlist name] [track position]
playlist favourites <-- playlist name

**Comment by umutxyp** [comment]
we will evaluate.
