### ISSUE TITLE
Problem with commands Play

### ISSUE THREAD

**Issue by Darioorfano** [umutxyp/MusicBot#27]
Hello, good day, I wanted to tell you that when I use the /play command on my discord server, the bot throws the name of the song twice, and twice on which channel it is playing, to carry out the test, I turned off the bot that I have heroku hosted so it doesn't mix with the one I have in my local environment, but the same thing still happens, any ideas? Thank you very much, Attached screenshot of the problem

![image](https://user-images.githubusercontent.com/54003477/186417643-c37b7c9e-9e8c-4c07-bbe2-c8aa906e383f.png)

**Comment by umutxyp** [comment]
A problem with the host or device you host your bot. It is not an issue with the project itself. This project is not yet a suitable project for heroku. Try refreshing your bot token and replit, glitch or paid virtual machines.
