### ISSUE TITLE
Error reloading application [/] commands

### ISSUE THREAD

**Issue by LestRocky** [umutxyp/MusicBot#29]
Everything works fine on the console, but the slash commands dont work and the error says:

BoxingMusic successfully connected.
ERROR EXAMPLE:IF THE BOT IS WORKING, RESPONDING TO COMMANDS BUT NO SOUND, FOLLOW THESE STEPS;
Enter the page of your project that you opened on replit.com.
Click on the one that says shell from the boxes that say console and shell above the opened box at the bottom right.
Type npm uni discord-player
Type npm i discord-player@5.3.0-dev.2
Type npm uni ytdl-core
Type npm i ytdl-core@4.10.0
Turn off and on the bot from the button that says "Stop" or "Run" in the middle of the replit screen
Connected MongoDB
Error reloading application [/] commands: DiscordAPIError[50035]: Invalid Form Body
11.options[0].options[1].description[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 100 in length.

**Comment by umutxyp** [comment]
Hello there. I downloaded the project as it is and wrote the token and mongodb url in the config.js file and installed the modules with the npm i console command. My bot is working without any problems, the reason for this error may be your bot, I have no idea. add the bot to your server with sufficient privileges admin etc.

**Comment by LestRocky** [comment]
okok
