### ISSUE TITLE
Feature request - Add command, listen and play from selected channel ID's

### ISSUE THREAD

**Issue by callum-isaac** [umutxyp/MusicBot#30]
Are you able to add a command to force bot to listen to commands from 1 channel?

And add a command to allow the bot to only play in 1 channel?

I've been using this the past couple days and WOW. Great work!

**Comment by umutxyp** [comment]
hey man, i was thinking of adding this command today. hahaha i will add it.

**Comment by umutxyp** [comment]
> Are you able to add a command to force bot to listen to commands from 1 channel?
> 
> And add a command to allow the bot to only play in 1 channel?
> 
> I've been using this the past couple days and WOW. Great work!

The command you requested has been added to the project. 
/channel add <channel>
/channel remove <channel>

updates files:
languages/en.js
languages/tr.js
events/interactionCreate.js

created files:
commands/channel.js
