### ISSUE TITLE
Spelling mistake - 

### ISSUE THREAD

**Issue by callum-isaac** [umutxyp/MusicBot#31]
https://github.com/umutxyp/MusicBot/blob/f5f81bc6cf75bf826fd719a4c7cc60e8c056e000/commands/play.js#L30

Hi, I think there is a spelling mistake in this line. "TWrite"

**Comment by umutxyp** [comment]
> https://github.com/umutxyp/MusicBot/blob/f5f81bc6cf75bf826fd719a4c7cc60e8c056e000/commands/play.js#L30
> 
> Hi, I think there is a spelling mistake in this line. "TWrite"

yep thank you i fixed.
