### ISSUE TITLE
Playlist causes bot to freeze/crash

### ISSUE THREAD

**Issue by callum-isaac** [umutxyp/MusicBot#32]
Hi, Sorry I keep making issue tickets :/

I create playlist - /playlist create (Name) Rock (public) True

Then I - /playlist add-music (playlist-name) Rock (name) https://open.spotify.com/playlist/1R2yVdmsa5R8wLBr2aEKHn

I can see they are in the playlist by running - /playlist list (name) Rock

All music shows. So I try to play the playlist and I it freezes, so I check terminal and get this error.

"**/home/container/node_modules/discord-player/dist/Structures/PlayerError.js:28
        Error.captureStackTrace(this);
              ^
InvalidTrack: [InvalidTrack] invalid track
    at new PlayerError (/home/container/node_modules/discord-player/dist/Structures/PlayerError.js:28:15)
    at Queue.addTrack (/home/container/node_modules/discord-player/dist/Structures/Queue.js:235:19)
    at Timeout._onTimeout (/home/container/commands/play.js:95:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  createdAt: 2022-08-31T16:35:27.122Z,
  statusCode: 'InvalidTrack'
}
Node.js v17.9.1**"

Have you experienced this issue? Can I not add playlist in this way?

**Comment by callum-isaac** [comment]
I can play the playlist if I do it this way - /play normal https://open.spotify.com/playlist/1R2yVdmsa5R8wLBr2aEKHn

**Comment by umutxyp** [comment]
> 

ı fixed. THANK YOU. 

updated files:
play.js 
playlist.js
