### ISSUE TITLE
ReferenceError: Res is not defined

### ISSUE THREAD

**Issue by HavaliRumuz** [umutxyp/MusicBot#42]
![image](https://user-images.githubusercontent.com/68316278/189287369-95b6424e-4cb3-443a-b251-20654f30f9af.png)
![image](https://user-images.githubusercontent.com/68316278/189287479-fcbde26b-2859-49b3-8720-a8356e4c1197.png)

**Comment by HavaliRumuz** [comment]
![image](https://user-images.githubusercontent.com/68316278/189287452-684f3e23-e6c7-44fa-906c-21f3cdcfa7cc.png)

**Comment by penchuri** [comment]
> ![image](https://user-images.githubusercontent.com/68316278/189287369-95b6424e-4cb3-443a-b251-20654f30f9af.png)
> ![image](https://user-images.githubusercontent.com/68316278/189287479-fcbde26b-2859-49b3-8720-a8356e4c1197.png)

Same error too

**Comment by umutxyp** [comment]
Hata düzenlendi. Teşekkürler. 

Yenilenen dosya: commands/search.js
