### ISSUE TITLE
Suggest 

### ISSUE THREAD

**Issue by penchuri** [umutxyp/MusicBot#44]
I think would be good it say song name 
![7998810E-A8AE-4069-A729-68C6DA14ABC5](https://user-images.githubusercontent.com/112509490/189402926-9f8604c7-20d1-4f24-80c0-d76cb927f932.jpeg)

**Comment by umutxyp** [comment]
https://github.com/umutxyp/MusicBot/blob/main/commands/resume.js 
I fixed the exact error and saw your notification ahahah thanks.
