### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by KickOfSilver** [umutxyp/MusicBot#54]
WARN: It looks like you didn't write the mongodb url? If you do not enter a valid mongodb url in the config.js file, you will not be able to use the bot.

Where will I find this?

**Comment by Fyxren** [comment]
Do you have your MongoDB URL? If not, you can find on your databases tab by clicking the "connect" button
![image](https://user-images.githubusercontent.com/68126277/200171496-bd7edf13-e1e8-4794-8e11-57c56701f279.png)

Then by clicking "Connect your application"
![image](https://user-images.githubusercontent.com/68126277/200171537-b54e1224-5497-43c3-8e65-7e60f3b33599.png)

Please keep in mind that if you'd use .env, that you will have to install it by hand. Came across this issue when helping someone trying to get this to work.
