### ISSUE TITLE
/play normal didn't work (no result found)

### ISSUE THREAD

**Issue by DevKilioZOfficiel** [umutxyp/MusicBot#60]
Since a few days, while I have not updated any package, when I run /play I have either:

```
An error encountered: PlayingError: FFmpeg/avconv not found!
Id: xQK0f6wzww8
Name: Video name
```

Either I have "undefined" in the console and "no result found"

Version: October Update

**Comment by umutxyp** [comment]
please make sure you have installed the ffmpeg and ffmpeg-static modules.
