### ISSUE TITLE
An error encountered: PlayingError: MC is not defined

### ISSUE THREAD

**Issue by b2210356054** [umutxyp/MusicBot#72]
Every time I use play normal command, for every song I tried I got this error.

**Comment by Die-Antwoord** [comment]
same error on my side, it also does this with Spotify.
```shell
An error encountered: PlayingError: MC is not defined
Id: 7CgQEvO4DDk
Name: Imagine Dragons - Easy Come Easy Go (Official Lyric Video)
```

**Comment by FaheemQuazi** [comment]
Can confirm as well, same error, and I don't see any references to a variable of that name to try and fix it. Any clues where to start?

**Comment by Die-Antwoord** [comment]
Ok so the bot is working again. but there is now this error in the command console

```shell
WARNING: ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
(node:26) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
``` 
It may be related to the issue.

**Comment by umutxyp** [comment]
this problem is fixed. Basically it wasn't from my project anyway.
