### ISSUE TITLE
/leave komutu

### ISSUE THREAD

**Issue by ali98bayram** [umutxyp/MusicBot#78]
selam üstad bota leave komutu eklemeye çalışıyorum herşey tamam ancak bir türlü başaramadım güncelleme gelirse eklermisin acaba?

**Comment by umutxyp** [comment]
> +1 bende uğraştım yapamadım



> selam üstad bota leave komutu eklemeye çalışıyorum herşey tamam ancak bir türlü başaramadım güncelleme gelirse eklermisin acaba?

Yakında 15.5 güncellemesi ile geliyor..
