### ISSUE TITLE
[Request] Save volume level

### ISSUE THREAD

**Issue by DasCanard** [umutxyp/MusicBot#83]
It would be great if there was an option to enable the volume level to be saved so the bot doesn't have to be set again and again when rejoining.

**Comment by DasCanard** [comment]
Another option would be, for example, that you can set a default volume.

**Comment by Godielvs** [comment]
I tried searching for like 30-40 minutes straight and coudn't find a way to change the default from 50 to something else (preferably 100). It would be great indeed.
