### ISSUE TITLE
Not playing music when hosting on ubuntu

### ISSUE THREAD

**Issue by devktd** [umutxyp/MusicBot#96]
I downloaded a music bot and tried to run it on my Windows computer. It worked fine, but when I tried to host it on my Ubuntu VPS, it only said 'Now playing:' and immediately said 'Queue is empty. You can play some more music, byebye... ✅'

![image](https://user-images.githubusercontent.com/66382438/220440336-59253bcf-9721-4503-9483-f9ac5ebc3546.png)

**Comment by EragonCity** [comment]
try uninstalling ffmpeg-static 
`npm uninstall ffmpeg-static`
`npm ci`
`npm update`
Then install ffmpeg using `npm install ffmpeg`. This worked for me
